name: DevSecOps Pipeline PHP

on:
  workflow_dispatch:

jobs:
  security-check:
    name: SAST Scan (Semgrep)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar Semgrep
        run: pip install semgrep

      - name: Rodar análise de segurança
        run: |
          semgrep --config=auto src/ --error